# -*- coding: utf-8 -*-
"""trYOLOv10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17qF1owu2Wzq8duk0L2px8QV2Sr1lFBQ7
"""

from google.colab import drive
drive.mount('/content/drive')
!nvcc --version

# Commented out IPython magic to ensure Python compatibility.
!pip install -q git+https://github.com/THU-MIG/yolov10.git
# %cd /content/drive/MyDrive/
!git clone https://github.com/THU-MIG/yolov10.git
# %cd /content/drive/MyDrive/yolov10
!pip install .
!pip install huggingface huggingface_hub
!pip install -U ultralytics

!yolo task=detect mode=train epochs=10 batch=6 plots=True model=/content/drive/MyDrive/datasets/weights/yolov10n.pt data=/content/drive/MyDrive/datasets/Tumor-1/data.yaml